return{
	Id="original",
	Name="Original",
	Source="Current GUI",
	Url="",
	Description="The current simplified control-panel style.",
	Tags={"default","current","simple"},
	Style={
		Primary=Color3.fromRGB(28,28,28),
		Stroke=Color3.fromRGB(76,76,76),
		Gradient=Color3.fromRGB(45,45,45),
		GradientOn=false,
		StrokeThickness=1,
		StrokeTransparency=0.55,
	},
	Theme={},
	Shape={
		WindowRadius=0,
		SectionRadius=0,
		ControlRadius=0,
		SliderRadius=0,
		SliderHeight=26,
		SliderStyle="original",
	},
}
